sonar.projectKey=taskroom
sonar.projectName=Taskroom
sonar.sources=backend,frontend/src
sonar.tests=backend/test
sonar.exclusions=**/node_modules/**,frontend/dist/**,**/coverage/**,backend/test/**/*.test.js
sonar.test.inclusions=backend/test/**/*.test.js
sonar.javascript.node.maxspace=512